# Generated by Django 2.2.16 on 2022-10-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_category_genre_genretitle_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'verbose_name': 'Жанры произведения', 'verbose_name_plural': 'Жанры произведения'},
        ),
    ]
