# Generated by Django 3.2.16 on 2022-10-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20221009_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('id',), 'verbose_name': 'Комментарий на отзыв', 'verbose_name_plural': 'Комментарии на отзывы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('id',), 'verbose_name': 'Отзыв на произведение', 'verbose_name_plural': 'Отзывы на произведения'},
        ),
    ]
