# Generated by Django 2.2.16 on 2022-10-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221005_1028'),
        ('reviews', '0007_auto_20221009_2103'),
    ]

    operations = [
    ]
