# Generated by Django 2.2.16 on 2022-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20221009_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='UNKNOWN', max_length=255, null=True, verbose_name='код подтверждения'),
        ),
    ]
