# Generated by Django 2.2.16 on 2022-10-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20221016_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
    ]
